
package com.nitish.teach.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloService", targetNamespace = "http://service.teach.nitish.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface HelloService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://service.teach.nitish.com/HelloService/printHelloMessageRequest", output = "http://service.teach.nitish.com/HelloService/printHelloMessageResponse")
    public void printHelloMessage(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
